### ISSUE TITLE
Larger box required

### ISSUE THREAD

**Issue by Anneli15** [chembl/IDG#100]
Can't fit the whole target type wording into the box and error is created i.e. can't be saved.

![screen shot 2015-12-16 at 2 57 03 pm](https://cloud.githubusercontent.com/assets/12811998/11844255/a422ba70-a405-11e5-8132-cc7fd32c4a85.png)

**Comment by mnowotka** [comment]
Yes, I can confirm this is a bug. The "target_type" field in IDG can currently only accept text that is 25 characters or less. Similar field in ChEMBL can handle text up to 30 characters and this should be changed in IDG accordingly.
