### ISSUE TITLE
adding targets

### ISSUE THREAD

**Issue by Anneli15** [chembl/IDG#102]
Hi
I've been adding and editing targets (complexes and families) in the target dictionary and suddenly i get an Error 500. Is there a problem with the web service at the moment? I see v 1.01

**Comment by revajk** [comment]
I don’t see any problem. and I just tired to edit (GRIA) as (GRIA)- test  and I didn’t face any problem. 
let me know the exact entry you are trying to edit and I can see why.

**Comment by Anneli15** [comment]
I'm trying to add this entry, GRIN1/GRIN2B protein complex. I've added earlier and I had no problem...

**Comment by Anneli15** [comment]
Added other targets earlier I meant

**Comment by revajk** [comment]
The entry is already there are you trying to edit them ? What should you edit to/?

**Comment by Anneli15** [comment]
Strange, so it has added it despite the error message. I logged out and back in again and can see it now. That's fine then.
