### ISSUE TITLE
editing target dictionary

### ISSUE THREAD

**Issue by ecibrian** [chembl/IDG#105]
When adding a new target, I am unable to add Target Name or Description if I have added it using the 'target ChEMBL ID'. I get a Server Error (500).

I've gone through some of the previous issues posted by Anneli but I cannot figure out why this is happening.

If you have time this week, it would be very helpful to get a quick intro on how does it work to add new targets, component sequences, what has to be done manually and what could be uploaded automatically...

Thanks

**Comment by mnowotka** [comment]
Fixed.
