### ISSUE TITLE
Component sequence when no ChEMBL target ID available

### ISSUE THREAD

**Issue by ecibrian** [chembl/IDG#106]
When there is a ChEMBL ID available for the target, the component sequence is automatically generated. 

What I have problems with is to create a new target which has not yet a ChEMBL ID. In this case I will find useful to have the following options to add the component sequence:
- Enter manually an UniProt ID that will automatically import the sequence and calculate the Sequence mdsum. If it is not possible to automatically include the sequence, I could work with either one of these two options, cut and paste the FASTA sequence or uploading a file with the FASTA sequence. 
- If the sequences can be retrieved automatically from UniProt, would it be possible to have also Db source and Db version automatically included?. 

I do not know how does it work to create ChEMBL target ID and how complicated it is. But the other option I can think of is to create ChEMBL cards for the missing targets and then add them to IDG. What do you think about this option?

**Comment by mnowotka** [comment]
I hope this is fixed now. If yes, please code this issue.

**Comment by ecibrian** [comment]
I am afraid that not. Now I cannot add new target dictionary..
I can open the page to create new target dictionaries but I get the server error (500) when I save it. I have no problem editing existing targets.

**Comment by ecibrian** [comment]
Back to 'Component sequence'. Now it does not load the protein sequence when I create a new one. I can see that all the other information is retrieved when introducing the UniProt ID, but not the protein sequence.

**Comment by ecibrian** [comment]
CHEMBL2364158

**Comment by ecibrian** [comment]
Q01344 this is for sequence component

**Comment by mnowotka** [comment]
All should be fixed now, please check.

**Comment by ecibrian** [comment]
Hi Michal, I will check it on Tuesday (I am only in from Tuesday to 
Thursday)

**Comment by ecibrian** [comment]
I am afraid, Server error (500)  (I am using version v. 0.1.7.) shows up again when trying to add a new target using UniProt accesion number.
Also, when adding the target using the ChEMBL target ID the Pref. name is again in capital letters.

**Comment by mnowotka** [comment]
Do you get error 500 for any accession number or for some specific number?

The task was not about changing the pref_name to lowercase but to change the interface behavior in such a way it ignores casing when performing checks, so you don't have to change the casing manually. Does it work?

**Comment by ecibrian** [comment]
reply below

**Comment by mnowotka** [comment]
Should be working now, please check.

**Comment by ecibrian** [comment]
I am afraid it does not work for me. Same error.

**Comment by mnowotka** [comment]
![screen shot 2016-04-19 at 15 53 03](https://cloud.githubusercontent.com/assets/837119/14643588/daf47f9a-0646-11e6-977e-21c62b7fb3ee.png)

**Comment by mnowotka** [comment]
Target Dictionaries should be fixed as well, please check.

**Comment by ecibrian** [comment]
It works now.
