### ISSUE TITLE
Unable to update molecule Status in 'Molecule dictionary'

### ISSUE THREAD

**Issue by ecibrian** [chembl/IDG#110]
I get a 'Server error (500)' when trying to update the 'Status' of the molecule in the 'Molecule dictionary".
Otherwise, I can create the new 'Molecule dictionary" without problems as long as I do not change the default 'Status'.

**Comment by mnowotka** [comment]
I just tried to do this on the production server and I succeeded without any problems:

![screen shot 2016-04-21 at 15 37 44](https://cloud.githubusercontent.com/assets/837119/14712971/3c65dc7e-07d7-11e6-94ee-48f18f5c9ebc.png)

Did it fail for any specific MD?

**Comment by ecibrian** [comment]
Could you try this one?
Reslizumab
Change status to 'Approved'

**Comment by ecibrian** [comment]
This one Lebrikizumab also gives me an error
But this one Oregovomav worked just fine a minute ago and could add it and edit its status and now I cannot change it, I get again 'Server error (500)'....

**Comment by mnowotka** [comment]
Yes, I can reproduce it, it will be fixed in 10 mins.

**Comment by ecibrian** [comment]
Thanks!

**Comment by mnowotka** [comment]
Should be fixed now (version 0.1.9), please verify.

**Comment by ecibrian** [comment]
Working now.
Thanks.
