### ISSUE TITLE
access to IDG interface

### ISSUE THREAD

**Issue by ecibrian** [chembl/IDG#112]
Hi Michal, I cannot access the IDG interface. Is it related to the recent shutdown?
Thanks

**Comment by mnowotka** [comment]
Yes, it is. Until nfs is fully recovered I won't be able to restart the interface I'm afraid.

**Comment by ecibrian** [comment]
Thanks. No problem. I just wanted to be sure it was not a problem on my side.

---

Elena Cibrian-Uhalte
ChEMBL - Biological Data Curator
EMBL-EBI
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD UK
Phone: +44 (0)1223494303
email: ecibrian@ebi.ac.uk

**Comment by mnowotka** [comment]
The interface is now back up and running, sorry for the inconvenience.
