### ISSUE TITLE
Add molecule synonym tab

### ISSUE THREAD

**Issue by Anneli15** [chembl/IDG#13]
The synonym field doesn't allow more than 10 characters which isn't enough.
![screen shot 2015-06-11 at 3 52 26 pm](https://cloud.githubusercontent.com/assets/12811998/8110048/1887053a-1052-11e5-8bd3-26593ec5b18f.png)

**Comment by revajk** [comment]
how much would you recon ? 50?

**Comment by Anneli15** [comment]
Yeah, that should be enough. Some trade names and INNs can be long so just need to cover for that.

**Comment by revajk** [comment]
done
