### ISSUE TITLE
Add company tab

### ISSUE THREAD

**Issue by Anneli15** [chembl/IDG#14]
Can you add more than one company here?

**Comment by mnowotka** [comment]
@Anneli15 - I think you have to be more specific here as I don't entirely understand the question? It can be interpreted as:
1. Can you add more then one company for the given compound? I don't think so, current relation is one-to-many (one company can have many compounds but a compound can have only one company) but @revajk has to confirm.
2. Can you add more companies using a company tab? Yes, as many as possible but each company had to have at least one compound defined.

**Comment by Anneli15** [comment]
Each compound often has more than one company that has developed /is developing it as drugs are frequently moved between/licensed to different companies. I guess adding them using add company tab and assigning them same compound would work fine, thanks.

**Comment by mnowotka** [comment]
Thanks for the clarification @Anneli15. @revajk - this may mean that we have to change this relation, but I would wait until Tuesday with such a change so we can discuss it and double check in person.

**Comment by revajk** [comment]
Yes you can add more than one company for a compound. But I am afraid, each company addition should be a separate entry for a given molecule. You can't add two companies in a single go.   @mnowotka company to compound is Many to many relation.
