### ISSUE TITLE
ATC codes

### ISSUE THREAD

**Issue by Anneli15** [chembl/IDG#15]
Where do these go? Under synonyms? It would actually be good if we could have a field for these, maybe in the Molecule dictionary tab where the Chembl/Pubmed/Drugbase ID is? In Chembl it is in a section called "Compound Cross References", in Wikipedia, ATC codes plus other ID:s are under header"Identfiers". So maybe it would be easier to have a "Other Identifiers" space instead a separate on for only PubChem ID (and leave Chembl ID separate as it is now)?

**Comment by revajk** [comment]
I can add a dictionary to hold all the identifiers (IUPHAR ID, CHEMSPIDER, PUBCHEM, ATCC , vet ATCC, Drugbank ID )and remove them from the  synonym type if that's Okie

**Comment by Anneli15** [comment]
Yes that sounds good, thanks!
