### ISSUE TITLE
Target dictionary

### ISSUE THREAD

**Issue by Anneli15** [chembl/IDG#16]
The issue with the target symbols MEK1 and MEKK1 (se below) brought up the question of target synonyms and if we can somehow incorporate the Chembl target synonym list into the web service? So for example, if I try to add the target MEK1, the system could ask me if I mean the HGNC symbol for target which is MAP3K1 (or any other target with potentially the same symbol)?
MEKK1 = MAP3K1 (HGNC approved symbol)
MEK1 = MAP2K1 (HGNC approved symbol)

Can't seem to be able to label this, wanted to say it is "enhancement"....

**Comment by Anneli15** [comment]
As discussed in the meeting this morning, this is another set of data that would be useful to add to the web services.

**Comment by revajk** [comment]
Does these have to go in target components? Can we get this from CHEMBL target components?

**Comment by Anneli15** [comment]
They would be target synonyms rather than components, we don't yet have a tab/space to add synonyms (I think), maybe worth adding at some point.
