### ISSUE TITLE
Write a function retreving data from ChEMBL.

### ISSUE THREAD

**Issue by mnowotka** [chembl/IDG#19]
Once we have determined which data we should fetch from ChEMBL as described in https://github.com/chembl/IDG/issues/18 we can start writing function to do this. The function should use ChEMBL web services (documentation here: https://www.ebi.ac.uk/chembl/ws and here: https://www.ebi.ac.uk/chembl/api/data/docs). If the function will be written in Python then https://github.com/chembl/chembl_webresource_client should be used to interact with web services, examples of usage can be found here: https://github.com/chembl/chembl_webresource_client/blob/master/chembl_webresource_client/tests.py

**Comment by revajk** [comment]
Step 1. Can retrieve data for molecule dictionary.  should take a CHEMBL Id and any required field and fetch all the relevant and available information from CHEMBL

**Comment by revajk** [comment]
Anneli, 

A quick question, in CHEMBL  we have a single tradename (IDG : Tradename US, EUR, JAP, CHI and a Tradename)  and a single research code (IDG has 4) 
which one should I populate them to?

**Comment by Anneli15** [comment]
Sorry, not quite sure I understand. Can you send me an example or screen shot please?

**Comment by revajk** [comment]
Okie there are two screen shots: One from IDG  synonym_type  
![screen shot 2015-09-10 at 15 00 40](https://cloud.githubusercontent.com/assets/12812161/9790401/c04f78f2-57cd-11e5-913a-989088658a81.png)

This is the synonym types from chembl:
![screen shot 2015-09-10 at 15 03 25](https://cloud.githubusercontent.com/assets/12812161/9790405/c524dd90-57cd-11e5-877a-f542279456f6.png)

IDG has RESEARCH_CODE _ALTERNATE_1, 2, 3, 4 and Tradenames US, EUR, JAP, CHI, Tradenames. but in chembl all it has are RESEARCH_CODE, TRADE_NAME.  My question is how should I populate them?

**Comment by Anneli15** [comment]
The spreadsheet is maybe a little too detailed so probably easier to add them as in chembl i.e. all under one headline to keep it uniform. Also, if we are getting synonyms from other resources like Chemspider, Pubchem etc then they don't really make a distinction between the country name or research codes.

**Comment by revajk** [comment]
That might cause inconsistency with the data that's already loaded. I might have to add RESEARCH_CODE and change the tradenames to TRADE_NAME.

**Comment by Anneli15** [comment]
So that would be an extra entry then or how would it work?

**Comment by revajk** [comment]
Yes research_code would be a extra entry

**Comment by Anneli15** [comment]
As "research code" is the same as "company code" in the spreadsheet and "molecule" in the data base, would it be possible to somehow to add the entries from chembl into the "Molecule" box as it is essentially the same entry (or should be)? Don't mind if the name is changed in the data base as long as the entries go into the same "box". So steer the research_code entries into the same place as "molecule". I'm not a script write so have no idea how that would work though.....

**Comment by revajk** [comment]
I can  do that I guess. But do you know what does the pref_name in CHEMBL means? At the moment I am using the pref_name for company_code. And querying the chembl_19 I found that the pref_name and  the research_code are not necessarily same always. 
![screen shot 2015-09-11 at 11 18 02](https://cloud.githubusercontent.com/assets/12812161/9812694/e9944108-5876-11e5-9c8f-8875165c5529.png)

**Comment by Anneli15** [comment]
I'll be the preferred name i.e. if it has a USAn/INN name then that is used in the title field ("compound name")

**Comment by revajk** [comment]
Question on target name: In the following link which one should I use as target name?

https://www.ebi.ac.uk/chembl/api/data/target?target_chembl_id=CHEMBL2311224

**Comment by mnowotka** [comment]
My guess would be `pref_name`.

**Comment by revajk** [comment]
I think those pref-names are not the 'standard' names. We don't have a target dictionary in the name "Bacterial DNA gyrase".

**Comment by agaulton** [comment]
The target pref_name is the standard ChEMBL name for a target, if that’s what you’re asking?

On 15 Sep 2015, at 22:45, revajk notifications@github.com wrote:

> I think those pref-names are not the 'standard' names. We don't have a target dictionary in the name "Bacterial DNA gyrase".
> 
> —
> Reply to this email directly or view it on GitHub.

Anna Gaulton

Senior Data Integration and Development Officer, ChEMBL
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom

Tel:  +44 1223 492690

ORCID: 0000-0003-2634-7400

**Comment by Anneli15** [comment]
Bacterial DNA gyrase is a "protein complex" so for these, just add the Chembl pref_name to be consistent (I have done this for other complexes an groups). In the description box I have then added the individual HGNC code for the group members.

**Comment by mnowotka** [comment]
I guess, `pref_name` is the best match here. We took `Target Dictionary` table directly from ChEMBL schema and eventually we will have to integrate our data with ChEMBL so using something else as a target name can only introduce confusion and more work for us during the integration.

**Comment by revajk** [comment]
Okie Thanks. So jus to make sure, if I have something like  Tyrosine-protein kinase ABL as target for a compound, then I add this to target name and leave the description as blank for now(i.e if we don’t have them in our DB already)

**Comment by mnowotka** [comment]
I hope @agaulton and @Anneli15 will be able to answer this question.

**Comment by Anneli15** [comment]
Yes, I think that would be fine. Assuming you mean complexes/families only now as the individual targets are already in the target dictionary? The target components can be added to the description but there is a tab for components, not populated at the moment. Wanted to look at that tab with you on Friday if that is OK?
