### ISSUE TITLE
Questions about some fields

### ISSUE THREAD

**Issue by Anneli15** [chembl/IDG#2]
![screen shot 4](https://cloud.githubusercontent.com/assets/12811998/8055635/ec0e37ae-0e98-11e5-8d8e-20de784992fa.png)
![screen shot 5](https://cloud.githubusercontent.com/assets/12811998/8055642/fe0e50d8-0e98-11e5-9793-60b4f30d352d.png)

Not sure what "Component" refers to in screenshot 4? Is it the target? 
In screenshot 5, what type of data are the fields "Detail description" and "Moa qualifier" for?

**Comment by revajk** [comment]
In our excel sheets, we don't have components and have never stored components. This has been created for future functionality. And the component relates closely to the ChEMBL component.

**Comment by ljbellis** [comment]
I believe the Component Type, if it is the same as in ChEMBL, should be filled with
Protein
or
RNA
etc

However, I could be wrong....
