### ISSUE TITLE
Write a function retreving data from chemspider

### ISSUE THREAD

**Issue by mnowotka** [chembl/IDG#20]
Similarly to https://github.com/chembl/IDG/issues/19 we should have a function to retrieve data from chemspider, python packages that can be useful are https://pypi.python.org/pypi/bioservices/1.3.6 and https://pypi.python.org/pypi/ChemSpiPy/1.0.4

**Comment by revajk** [comment]
Are we doing with Chemspider ID or by smiles or inchikey?

**Comment by mnowotka** [comment]
We don't have Chemspider ID when calling Chemspider API. We also don't want to store Chemspider ID. We want to use Chemspider API to search compound by its structure (SMILES, InChI, InChI Key, name, synonym) and get some data that IDG database requires.

**Comment by revajk** [comment]
OKIE. Thanks

**Comment by mnowotka** [comment]
Sorry, there was a mistake in my comment above, it's now corrected.

**Comment by revajk** [comment]
Yes The CID\d+(that we have in our IDG DB)  is not CHEMSPIDER IDs I suppose.  I have asked anneli to give me some example Ids

**Comment by revajk** [comment]
Sorry I mean, only numbers are used to identify the compounds in API.  And we have already got some CIDs store in place of  CHEMBL ID ( i guess those molecules are from Chemspider) .

**Comment by mnowotka** [comment]
Not true. You don't need CID, CHEMBL ID, Chemspider ID or any other ID to search Chemspider. In fact this is the reason I asked to write this function. You can search Chemspider by structure or name (or synonym). Look at the client documentation: https://github.com/mcs07/ChemSpiPy, note this code example:

```
from chemspipy import ChemSpider
cs = ChemSpider('<YOUR-SECURITY-TOKEN>')
c2 = cs.search('benzene')  # Search using name, SMILES, InChI, InChIKey, etc.
```

**Comment by revajk** [comment]
YES. My question was different. I shall explain to you when I see you tomorrow.

**Comment by revajk** [comment]
Anneli, Have you tested the Chemspier lookup? Other than the save - edit function have you got any other concern?

**Comment by Anneli15** [comment]
I've tested it and it seems to work. Adding inchl key fetched the structure and name, not synonyms or cross reference though? Can't check chembl lookup at the moment, gives me an 500 error again?

**Comment by revajk** [comment]
Could you send me the compound you tested in Chembl lookup. Chemspider doesn’t have synonyms or cross-reference.

**Comment by Anneli15** [comment]
CHEMBL127071

**Comment by revajk** [comment]
Anneli, The error is because the compound is already there. I will let you  know once  i fix it.

**Comment by Anneli15** [comment]
Ok. Used that compound because it has a couple of synonyms in chembl. Doesn't look like chembl lookup fetches synonyms yet?

**Comment by revajk** [comment]
Have you never seen Synonym populated While using ChEMBL lookup? I tried to delete the compound in local server and do chembl lookup I did get synonym and structure(inchi and smiles) added. 

Reva.

**Comment by Anneli15** [comment]
Yes, it works, have tested with compound that is not in the system. May have been a synonym that wasn't related to the chembl ID that I couldn't see. And no more error 500 when saving, thanks!
