### ISSUE TITLE
Write a function retreving data from other sources

### ISSUE THREAD

**Issue by mnowotka** [chembl/IDG#21]
Apart from Chembl (https://github.com/chembl/IDG/issues/19) and chemspider (https://github.com/chembl/IDG/issues/20) maybe there exist more useful online data sources. We should identify them and add relevant functions as well.

**Comment by Anneli15** [comment]
Link to one source for compound IDs and synonyms. Not sure how available the data is for use for our database though?
http://chem.sis.nlm.nih.gov/chemidplus/
