### ISSUE TITLE
Adding info to drugs

### ISSUE THREAD

**Issue by Anneli15** [chembl/IDG#25]
Tried to add some additional info to the drugs I had previously entered and got the error message below.
Ok, same message for everything I try to click, is the service down?

![screen shot 2015-06-23 at 10 27 34 am](https://cloud.githubusercontent.com/assets/12811998/8303005/acd5c7be-1992-11e5-9405-59f262e80ffa.png)

**Comment by revajk** [comment]
got them Anneli. give me 30 min in a meeting will push the site live. 

Reva.

**Comment by Anneli15** [comment]
OK.

**Comment by revajk** [comment]
Anneli, should be available now. 

And have edited the columns so that they show the molecule name.
