### ISSUE TITLE
Django command for importing Excel spreadsheets

### ISSUE THREAD

**Issue by mnowotka** [chembl/IDG#3]
Since Anneli provided some initial data in a form of xml spreadsheets we need to have some ability to import it to the IDG database. This should be implemented as Django command using models defined for IDG.

**Comment by revajk** [comment]
Have added the dictionary tables. Status,  Synonym, target and Mechanism. should be available.

**Comment by mnowotka** [comment]
Sorry, I don't quite understand...

**Comment by mnowotka** [comment]
All excel spreadsheets are loaded now.
