### ISSUE TITLE
Add molecule synonym tab

### ISSUE THREAD

**Issue by Anneli15** [chembl/IDG#30]
Making upload file compulsory won't work as not many of the synonyms will be in a file. UNII codes, extra registration codes etc would be added manually one by one. Only when there are loads of one type of synonyms (like clinical trials IDs or sometimes trade names) would I need the "upload file" option.

![screen shot 2015-07-20 at 10 24 47 am](https://cloud.githubusercontent.com/assets/12811998/8773155/fc123348-2ec9-11e5-8439-d942c8c41c52.png)

**Comment by revajk** [comment]
Thanks Anneli, I will change them before I push them live then. 

Reva.
