### ISSUE TITLE
cross references

### ISSUE THREAD

**Issue by Anneli15** [chembl/IDG#32]
I can't see how to add cross references to specific compound. Maybe we can look at this on Wednesday.

Also wanted to ask where the target dictionary comes from as there are missing targets that are in Chembl. I thought you got it from there but maybe misunderstood?

**Comment by revajk** [comment]
The targets are form the excel sheet that you gave me. New Targets can be added through TargetDictionary Page. If you can’t add them let me know I can look in to it. 

Reva.
