### ISSUE TITLE
newly loaded data

### ISSUE THREAD

**Issue by Anneli15** [chembl/IDG#35]
Not sure where these compounds come from and why they are labeled with -4, -3, etc as highest phase?
![screen shot 2015-08-12 at 11 40 40 am](https://cloud.githubusercontent.com/assets/12811998/9222136/34b60ee8-40e7-11e5-92b1-c7b01087306e.png)

**Comment by revajk** [comment]
They are from Johns spreadsheet. And I think we agreed  initially to load Johns set as it is. 
Do you want them to be removed.

**Comment by Anneli15** [comment]
No, just leave them for now. I can't see them on the spreadsheet I have so was just wondering. Guess he sent me a different version, maybe you can send me the one you have?

**Comment by revajk** [comment]
KI spreadsheet.

**Comment by Anneli15** [comment]
Can’t see it, I’m missing something….:-)

**Comment by Anneli15** [comment]
I’ve changed the -4 to 4, have checked some of them and seems that they were given the - by mistake.

**Comment by revajk** [comment]
Super! Thanks for validating them.
