### ISSUE TITLE
kinases

### ISSUE THREAD

**Issue by Anneli15** [chembl/IDG#37]
There doesn't seem to be Chembl IDs for any of the kinase inhibitors? Some of the compounds won't have one but most do.

**Comment by revajk** [comment]
There wasn’t any chembl ID  provided in the spreadsheet.

**Comment by Anneli15** [comment]
Not sure why you didn’t have any IDs. Attached is the spreadsheet I have.

**Comment by revajk** [comment]
send as a  email I can’t see the attachment
