### ISSUE TITLE
Loading GPCR data from Excel to IDG interface.

### ISSUE THREAD

**Issue by mnowotka** [chembl/IDG#38]
We would like to load GPCR data from Excel spreadsheets into IDG. Since we don't have spreadsheets yet, I'm assigning Anneli for this task and I will reassign this to Reva when we'll get the spreadsheets.

**Comment by mnowotka** [comment]
This comment is just to notify @revajk that this issue has been created :)

**Comment by mnowotka** [comment]
We have data now, assigning @revajk .

**Comment by revajk** [comment]
Have loaded GPCRs. Anneli, Could you let Michal know if you have any loss of data. We have a backup now and should be able to restore, if we have any data loss.
