### ISSUE TITLE
Load any missing data to the inteface.

### ISSUE THREAD

**Issue by mnowotka** [chembl/IDG#42]
If I understand correctly Anneli was using Excel spreadsheets during the period when IDG interface was switched off. I assume the spreadsheets are in ChEMBL dropbox folder. We should load it to the interface now. @revajk - should you have any problems with identifying new data, please ask @Anneli15  for help.

**Comment by revajk** [comment]
Hi Anneli, Where have you got the recent data in dropbox?

**Comment by mnowotka** [comment]
Is this issue resolved?

**Comment by Anneli15** [comment]
Yes, the data is loaded
