### ISSUE TITLE
Delete 'notes' file from models directory

### ISSUE THREAD

**Issue by mnowotka** [chembl/IDG#48]
There is an empty file called 'notes' (without file extension) in the models directory:

http://sark.ebi.ac.uk:9090/?p=idg.git;a=blob;f=idg/models/notes;h=e69de29bb2d1d6434b8b29ae775ad8c2e48c5391;hb=HEAD

I don't think we need it. Please delete it.

**Comment by mnowotka** [comment]
There is another empty file called 'status_typ'. Please delete is as well.

**Comment by revajk** [comment]
Done
