### ISSUE TITLE
Can't change entry

### ISSUE THREAD

**Issue by Anneli15** [chembl/IDG#49]
Trying to make changes to an entry (GLYX-13) but get a message saying server error 500

**Comment by Anneli15** [comment]
Ok, can't add compounds either so guess server is down?

**Comment by mnowotka** [comment]
This is interesting, as it works for me :)
Just double checking, are you using this URL: http://sark.ebi.ac.uk:8484/idg/ ?

**Comment by Anneli15** [comment]
Yes I am. Have tried logging out and in again a couple of times but doesn't seem to make any difference. Anything else i can try?

**Comment by Anneli15** [comment]
http://sark.ebi.ac.uk:8484/idg/idg/moleculedictionary/add/

**Comment by revajk** [comment]
I think it has to do with the CHEMBL look up. while adding a compound I could add them with just giving a CHEMBL Id and hitting save. But I get a 500 error when trying to edit already existing compound.

**Comment by mnowotka** [comment]
OK, so when you say you've successfully logged out and in again, this means that you can see the interface (so it's not down) it's just some specific parts that fail?

**Comment by Anneli15** [comment]
I've tried making a change to entry and adding new molecule. I'll try something else...

**Comment by Anneli15** [comment]
Ok, so added description to target dictionary and that works so yes, seems something is wrong with some specific parts like the molecule dictionary.

**Comment by revajk** [comment]
Could you try to add a compound with a CHEMBL id and with out filling any other fields and save.  and let me know if you have any problems with that too.

**Comment by Anneli15** [comment]
Still get server error 500

**Comment by revajk** [comment]
Have updated the scripts. Should work fine now. Could you check this and let me know.

**Comment by Anneli15** [comment]
I managed to change an entry but still can't add a new compound..

**Comment by revajk** [comment]
Trying clearing your history and try again . I had the same issue and it works fine now

**Comment by Anneli15** [comment]
How do I clear history?

**Comment by revajk** [comment]
which browser are you using?

**Comment by Anneli15** [comment]
safari

**Comment by Anneli15** [comment]
I see, you mean browser history. ok

**Comment by Anneli15** [comment]
sorry, still doesn't work.

**Comment by revajk** [comment]
hmm that's weird, I just logged in as you and it works fine for me. clear your Cache and see if that would help. May be, Michal could suggest something that would help

**Comment by mnowotka** [comment]
I'm not a safari user. Maybe you can try FireFox instead? Using FireFox could help us in future as it has many plugins helfpul when debugging.

**Comment by Anneli15** [comment]
Seems to work now, have just added a compound to the dictionary. Happy to switch to using firefox, have used that before but not on this Mac as safari has been fine....

**Comment by mnowotka** [comment]
I guess safari is fine even now but cache still exists :)
I can't tell you how to clean cache in safari but in firefox you can always use cmd+shift+r

Once you have firefox installed, can you install following add-ons:
https://addons.mozilla.org/en-US/firefox/addon/firebug/
https://addons.mozilla.org/en-US/firefox/addon/measureit/
https://addons.mozilla.org/en-US/firefox/addon/colorzilla/
https://addons.mozilla.org/en-US/firefox/addon/jsonview/

You don't need to know what they all are doing, but they might help us in future.

**Comment by Anneli15** [comment]
Ok, so everything else seems to work except adding molecule synonym. The look up looks good, the system added smiles and inch key nicely :-)

**Comment by Anneli15** [comment]
Ok, will add firefox and add-ons

**Comment by revajk** [comment]
The synonyms  I am still working on.I wasn’t handling the compounds without synonyms well. Will update them soon

**Comment by Anneli15** [comment]
Ok, will leave that bit for now and add later. By the way, chembl look up brings back the structure related items but not synonyms or other IDs (IUPHAR, chemspider etc). Will that happen eventually? Also, is the upload of note files with for example clinical trials IDs still on your lists of things to do? Can't see the option yet but may have missed it.

**Comment by Anneli15** [comment]
I guess because of chembl lookup, the system won't let me add compounds without a chembl ID.... Anyway around this?

**Comment by revajk** [comment]
Should be able to do that now.
