### ISSUE TITLE
Question about loaded data

### ISSUE THREAD

**Issue by Anneli15** [chembl/IDG#50]
I was wondering, the data that you loaded recently for me (ion channel active compounds) doesn't seem to have any details like structure, references, mechanism etc. Is there a reason for why this hasn't loaded? `The compounds are in the molecule dictionary but no other tabs seem have any data. 

Also, there seem to be a default "YES" for prodrug and "NO" for black box warning. If there is no information about this status, could the default be "unknown" please?

**Comment by revajk** [comment]
Yes Anneli,  Not all the data are loaded yet. I will let you know once they are loaded. I think the data has got some special characters in there and the script keeps dying 
I will let you know once they are fully loaded. 

Reva.

**Comment by Anneli15** [comment]
OK, thanks. What about the default choices for prodrug and black box?

**Comment by revajk** [comment]
I have changed them now. You should see them once I deploy them to the servers.

**Comment by mnowotka** [comment]
Hi, is this completed?

**Comment by revajk** [comment]
Yes all the ion channels are now loaded.

**Comment by mnowotka** [comment]
Thanks Reva. @Anneli15, if this satisfies your requirements, please close this issue.

**Comment by Anneli15** [comment]
I can't see all the data in my version, only the compounds. Still missing structure, references, mechanism etc.

**Comment by revajk** [comment]
I am deploying now I will let you know once I finish them

**Comment by mnowotka** [comment]
OK. Please keep in mind that my definition of 'completed' is tested and deployed to production.

**Comment by Anneli15** [comment]
Was adding some details to loaded compounds and noticed that the details of the ion channel compounds are still missing ( except name and Chembl ID etc = "first page" in Molecular dictionary). No targets, references etc. Actually, also true for some kinase inhibitors, seems that this problem concerns compounds loaded in September (02/09 and 07/09) as Aug 25th is OK? Only compound info in the database on September loaded molecules is the data manually added by me. Have re-opened this issue.

**Comment by Anneli15** [comment]
The pro-drug and black box issue is still unresolved too ie all compounds seem to be prodrugs, should be made either unknown or preferrably "No". Have changed some manually but too many of them....

**Comment by revajk** [comment]
Okie! Let me make this clear. This should be the case of a trial process this morning as I took a dump from production and loaded on to the local and made recent changes and deployed again. I have missed to reload the ion_channels. I will replied them now. 

Reva.

**Comment by revajk** [comment]
@Anneli15 , Ion channels are now loaded. and I had add few target dictionaries manually as the complex  where not there(eg.CHRNA3/CHRNB4). I haven't updated any other details other than name. CHEMBL lookup prodrug/blackbox  should be fixed now.

**Comment by Anneli15** [comment]
Ok, thanks. Will have a look in a minute if the system is ready.

**Comment by revajk** [comment]
Yes the system is ready. Should be able to view the data.

**Comment by Anneli15** [comment]
Looks good, thanks Reva.

**Comment by revajk** [comment]
In the excel sheet, for a compound if the prodrug column  is empty -  does that mean it is Not a prodrug or is it Unknown?

**Comment by Anneli15** [comment]
It means it's not a prodrug.

**Comment by revajk** [comment]
Thanks ! you still working :-)

**Comment by Anneli15** [comment]
:-) I check my mails, bad habit not to switch off....
