### ISSUE TITLE
adding data to specific compound

### ISSUE THREAD

**Issue by Anneli15** [chembl/IDG#51]
We need to have a look at the way the selection boxes work. At the moment, if I'm adding say a company to a compound, I have to start typing the first few letters in the box to get at the entry I want to add to (see screen shot). 
![screen shot 2015-09-15 at 11 11 55 am](https://cloud.githubusercontent.com/assets/12811998/9874044/b2377ad6-5b9b-11e5-980f-faed2444c5ad.png)

If I delay, it reads the 3rd or 4th letter as a starting point. Also, more complex, when adding a mechanism reference, I have to type "antagonist then space then compound name in rapid succession to find the entry I want to add to. This is not very easy, especially as the box is small and there a loads of entries. Alphabetical order based on compound rather than mechanism type? Can entries be added to a specific compound without leaving the "compound page" so to speak? Relating to this, it would be good if I could go back to the compound page when adding data instead of having to go back to molecule dictionary, find compound entry and then add another. I'm sure there was a way to do this before i.e. clicking on the compound name at the top (see screen shot)? Maybe discuss all this on Friday when I'm in the office but thought I'd put it down here so I don't forget.

![screen shot 2015-09-15 at 11 11 33 am](https://cloud.githubusercontent.com/assets/12811998/9874070/cc4455d4-5b9b-11e5-9522-59fd2e611a19.png)

**Comment by mnowotka** [comment]
The reason why we have this box instead of drop down is that this allows us to choose several molecules instead of single one. We might think about changing this to some nicer component and for now just to make it wider.
