### ISSUE TITLE
Extended boxes

### ISSUE THREAD

**Issue by Anneli15** [chembl/IDG#52]
Will need larger box size (allow more characters and extend so writing can be seen) in target dictionary too (see screen shot).

![screen shot 2015-09-17 at 10 55 27 am](https://cloud.githubusercontent.com/assets/12811998/9930315/c99ef5ba-5d2a-11e5-9ce3-ac1e9dac2e65.png)

**Comment by revajk** [comment]
Could you check whether these boxes are wide enough?

**Comment by Anneli15** [comment]
No, they don't look any different.
