### ISSUE TITLE
Separate CHEMBL_IDs from CIDs in Molecule Dictionary.

### ISSUE THREAD

**Issue by mnowotka** [chembl/IDG#53]
Currently in MoleculeDictionary we have a chembl_id column but it stores chembl_ids and cids.
We should change this:
1. Create cid table
2. Move all the cids from chembl_id to cid column and clear chemb_id values for those records.
3. For the records that have only cid try to find chembl_id and fill it.
4. Add some django Form/field validation stuff (https://docs.djangoproject.com/en/1.8/ref/forms/validation/) so that chembl_id column accepts only values that begin withc CHEMBL followed by number and cid column accepts only values that begin with cid and followed by number.

**Comment by revajk** [comment]
I have a command to update the fields. And while looking to find the ChEMBLID for a CID (CID45381907 and few others) the pubchem has linked them sureChEMBLl ID  and not a ChEMBL id. Should I leave them blank if I can't find a chembl id ?

**Comment by Anneli15** [comment]
Guess so as sureChembl isn't the same as Chembl ID (unless we have anther column for this). Linking Chembl to CID should be as straight forward as a sureChembl ID, isn't that so? Both are "external" IDs (except sureChembl a bit less external....)

**Comment by revajk** [comment]
Yes I thought so, But the webpage doesn’t provide information on CHEMBL ids. But they have SureChEMBL and ChEBIs .

**Comment by Anneli15** [comment]
But we have the CID? We can add surechembl ID or chebi IDs as cross reference, new type, if there isn't either Chembl ID, CID, chemspider ID etc. Therre will be a few compounds that won't have any structural information or IDs, these may eventually get them if the compound is developed further. Should be able to pdate system with any new inforation available at some point. Not sure how this would work practically though.

**Comment by revajk** [comment]
okie That makes sense. I can add two new cross reference types and link them to the Cids.
