### ISSUE TITLE
Create structure_key column

### ISSUE THREAD

**Issue by mnowotka** [chembl/IDG#54]
We need a structure_key in MoleculeDictionary in order to be able to make a structure lookup in ChEMBL and Chemspider. This is related to #19 and #20.

**Comment by revajk** [comment]
The structure key you fill in to search the Chempsider- do you want to store them? Because eventually they do get updated to the Molecule structure. So, should we have to have them in Molecule dictionary as well?

**Comment by mnowotka** [comment]
Where else would you like to put `structure_key`?

**Comment by revajk** [comment]
May be I got them wrong, Input to structure key( to search in Chemspider ) is inchi, inch_key, smiles right ? Then these are stored in Molecule Structure table. 

If none of those are not a input to search Chemspider - What is?
