### ISSUE TITLE
Target component tab

### ISSUE THREAD

**Issue by Anneli15** [chembl/IDG#55]
Addition of table to illustrate and compile target components of protein families and complexes. 
Target: 
- Name of the protein complex/family manually added (changed) into the target dictionary 
- Would be Chembl pref_name if available or, if not in Chembl, other appropriate name
  Example: Glutamate receptor ionotropic kainate

Type: 
Components: would be the 
- Individual proteins (already in the target dictionary)
  Example: Glutamate receptor ionotropic, kainate 1     GRIK1     P39086

![screen shot 2015-09-18 at 11 51 20 am](https://cloud.githubusercontent.com/assets/12811998/9957915/51744626-5dfc-11e5-93fc-0695011c5faf.png)

Chembl:s pref_name used for individual targets (proteins) are the Uniprot names whereas I've used the HGNC description (and these are now in the data base). Should we change these to the same that are in Chembl? I'm happy with either, was just thinking about keeping it the same and for look purposes so maybe change them to be the same as in Chembl?

**Comment by mnowotka** [comment]
Hi @Anneli15,
With the recent changes implemented, do you think we can close this issue now?

**Comment by Anneli15** [comment]
What is this?
![screen shot 2015-10-23 at 12 10 09 pm](https://cloud.githubusercontent.com/assets/12811998/10691180/235fae26-797f-11e5-93e8-587a977a7968.png)
INSR was the new target, not sure it should show up here?

**Comment by mnowotka** [comment]
Yes, I don't understand why there is a single target component in target components table, I've already asked @revajk elsewhere.

**Comment by Anneli15** [comment]
ah yes, see that now.

**Comment by Anneli15** [comment]
I think the target components will only make sense (and be populated) when we load in protein families using Chembl IDs for these as they will have target components. At the moment, families are marked with ( ) around a symbol. There are a few of these and most if not all of them are in Chembl (with target components annotated) so should be ok?

**Comment by Anneli15** [comment]
Ok, that was maybe a bit confusing but please see screen shot above and you may understand 
what I mean.

**Comment by revajk** [comment]
The target_components I will load them now.  Sorry , I had a wrong understanding of adding the target components as and when adding the Mechanism through lookups. And back populate the rest. 
I will try to load the whole target components now. 

https://www.ebi.ac.uk/chembl/api/data/target?target_chembl_id=CHEMBL1981 https://www.ebi.ac.uk/chembl/api/data/target?target_chembl_id=CHEMBL1981 Should I not  add target_component when doing chembl lookup? 

Thanks
