### ISSUE TITLE
Retreive synonyms from PubChem

### ISSUE THREAD

**Issue by mnowotka** [chembl/IDG#60]
A source of potential synonyms.
The client exists: https://pypi.python.org/pypi/PubChemPy/1.0

**Comment by mnowotka** [comment]
We should also get `pubchem_id` from here.

**Comment by revajk** [comment]
if  I have  a list of synonyms like this : u'8(S)-HETE', u'8S-HETE', u'(5Z,8S,9E,11Z,14Z)-8-hydroxyicosa-5,9,11,14-tetraenoic acid', u'98462-03-4', u'8(S)-hydroxyeicosatetraenoic acid', u'8S-hydroxy-5Z,9E,11Z,14Z-eicosatetraenoic acid', u'8(S)-Hydroxy-(5Z,9E,11Z,14Z)-eicosatetraenoic acid', u'(5Z,9E,11Z,14Z)-(8S)-8-Hydroxyeicosa-5,9,11,14-tetraenoic acid', u'(5Z,9E,11Z,14Z)-(8S)-8-Hydroxyicosa-5,9,11,14-tetraenoic acid', u'8-Hete', u'(5Z,8S,9E,11Z,14Z)-8-hydroxyicosa-5,9,11,14-tetraenoate', u'AC1NR1N8', u'8 -HETE', u'H4019_SIGMA', u'BML1-B04', u'GTPL2679', u'CHEBI:34486', u'HMDB04679', u'NLUNAYAEIJYXRB-VYOQERLCSA-N', u'1505AH', u'LMFA03060006', u'NCGC00161238-01', u'FT-0642370', u'8S-hydroxy-5Z,9E,11Z,14Z-eicosatetraenoate', u'C14776', u'8(S)-Hydroxy-(5Z,9E,11Z,14Z)-eicosatetraenoate', u'3B3-024569', u'(8S)-hydroxy-(5Z),(9E),(11Z),(14Z)-eicosatetraenoic acid', u'(S)-(Z,E,Z,Z)-8-hydroxyeicosa-5,9,11,14-tetraenoic acid', u'(5Z,8S,9E,11Z,14Z)-8-hydroxyeicosa-5,9,11,14-tetraenoic acid'. Could you suggest me how I categorise them to the synonym_type or reference_type ? I can't seem to figure out anything else other than the obvious (inchi and CHEBI)

**Comment by Anneli15** [comment]
It is  phase 0 compound and endogenous ligand so it will probably be removed when I get to QC these... But for other similar, you will have to grouped them under "Synonym or retired INN/USAN" and maybe the name for this type could be "Synonyms" only (like in Chembl)?

**Comment by revajk** [comment]
I didn't quite understand that. 
But That's an example data. It would be helpful if you can suggest me what pattern to look for grouping them in a general context. 

like, if it starts with CHEBI - chebi reference_type, 
if it starts with LMFA - then this mean this category .. like that. 

OR do you want me to add them all to Synonyms or retired INN/USAN name if I am not sure of category?!

**Comment by Anneli15** [comment]
Yes, I think that would be best as category won't be easy to add. For example, 98462-03-4 is a CAS number. PubChem doesn't put these into any particular type/group (at least not on the web page) and only lists them as synonyms. Some are ID:s from vendors, some chemical names. Should we group them into a synonym type "PubChem synonyms"...?

**Comment by mnowotka** [comment]
You can distinguish between CHEBI and InChi as you said. For the CAS you can use this regex from my twitter bot script:

```
CAS_NUMBER_REGEX = re.compile(r"\d{5,7}\-\d{2}\-\d{1}")
```

More complicated regex is used to find research codes:

```
re.compile(r"(^|\s)+([A-Z]+(\-|\.|\s)?[A-Z]{0,4}[\d]{2,}(\-|\.|\s)?[a-zA-Z]{0,4})((,|;)*\s*([A-Z]+(\-|\.|\s)?[A-Z]{0,4}[\d]{2,}(\-|\.|\s)?[a-zA-Z]{0,4})*)*(\n|$)")
```

It might be hard to distinguish between INN and USAN name but it's easy to distinguish  that this is USAN _or_ INN and _not_ something else.

**Comment by Anneli15** [comment]
If you are not sure or not clear what they are, into "synonyms and retired INN/USAN".

GTPL2679: GTPL2679 is the same as IUPHAR ID 2679
SIGMA is Sigma Aldrich ID plus there are a few other vendor IDs too
HMD = Human Metabolome Database id
etc.
Some are permutation of the same name (LY353381 LY 353381 LY-353381). Synonym list could be long but that is OK.

**Comment by Anneli15** [comment]
On second thought, if possible to ignore vendor IDs then that would be good (sigma and likes)

**Comment by revajk** [comment]
OKIE! Thanks both.  so anything with GPL\* I add them to IUPHAR ID? And leave the one that ends with SIGMA.

**Comment by Anneli15** [comment]
yes, think that will be OK. Will also add iuphar IDs to compounds that haven't had these like the kinase inhibitors

**Comment by revajk** [comment]
Yes. Pub chem now filter synonyms and cross reference from pubchem.
