### ISSUE TITLE
Add accession and ChEMBL ID fields to the Target Dictionary table.

### ISSUE THREAD

**Issue by mnowotka** [chembl/IDG#62]
In order to be able to do a lookup described in #61 we need to have some identifier. Since we are planning to use ChEMBL as a source of our data ChEMBL ID seems to be the best choice. We should also add accession field to keep reference to Uniprot.

**Comment by mnowotka** [comment]
I can see they are added now but not visible by default. Please make them visible as well.

**Comment by mnowotka** [comment]
Is this done?

**Comment by revajk** [comment]
Yes.
