### ISSUE TITLE
molfile in the molecule structure table - do we need it?

### ISSUE THREAD

**Issue by mnowotka** [chembl/IDG#67]
I've just noticed that `molfile` column in the Molecule Structure table is always empty. Do we need it at all? If no, we should drop the column, if yes - we should put some logic that will fetch/generate molfile if missing.

**Comment by Anneli15** [comment]
I don't collect this info, probably from chembl? Don't think we need it in IDG.

**Comment by mnowotka** [comment]
OK, let's remove it then.

**Comment by mnowotka** [comment]
OK, during writing the migration script I've found that having a molfile in the database would be very helpful, so we have to keep it and fill it immediately after new compound is created, just like with other structure identifiers, as described in https://github.com/chembl/IDG/issues/66. I'm not closing this issue yes, so I can discuss it during our Friday catch-up.
