### ISSUE TITLE
Add predefined choices to molecule_dictionary.drug_type

### ISSUE THREAD

**Issue by mnowotka** [chembl/IDG#69]
If you do:

```
select distinct(drug_type) 
from idg_moleculedictionary;
```

You willl get:

```
Small Molecules
SmallMolecules
Peptide
Small molecule
```

This is not correct. There should be a predefined list of choices (Django model CHOICES) so the user can only choose from those. Please ask @Anneli15 , what items should this list of choices contain.

**Comment by Anneli15** [comment]
We could make it simple and just have:
Small molecule
Biological
or
check in chembl under "Drug type" and add the types that are in the system (like mAb, oligopeptide etc)
