### ISSUE TITLE
Actual values of molecule synonsyms are out of possible choices

### ISSUE THREAD

**Issue by mnowotka** [chembl/IDG#71]
If I do the following query:

```
select distinct(description) 
from idg_synonymtype;
```

I will get:

```
Research Code Alternate 1
Research Code Alternate 2
Research Code Alternate 3
Research Code Alternate 4
Synonym or retired INN/USAN
Trade_name
Tradename US
Tradename EUR
Tradename JAP
Tradename CHN
Vet ATCC
ID
Research_code
```

Now in `idg/models/molecule_synonym.py` file possible choices defined for the synonym type are:

```
SYNONYM_TYPE_CHOICE = (
    (1, 'Research Code Alternate 1'), # RC
    (2, 'Research Code Alternate 2'), # RC
    (3, 'Research Code Alternate 3'), # RC
    (4, 'Research Code Alternate 4'), # RC
    (5, 'CAS Registry number'), # CAS
    (6, 'Synonym or retired INN/USAN'), # USAN_R
    (7, 'Tradenames'), # TN
    (8, 'Tradename US'), # TN
    (9, 'Tradename EUR'), # TN
    (10, 'Tradename JAP'), # TN
    (11, 'Tradename CHN'), # TN
    (12, 'DrugBank ID'), # ignore
    (13, 'IUPHAR ID'), # ignore
    (14, 'ClinicalTrials ID'), # ignore
    (15, 'ATCC'), # ATC
    (16, 'Vet ATCC'), # ignore
    (17, 'Chemspider ID') # ignore
)
```

So it looks like `ID`, `Trade_name` and `Research_code` should never exist in the database because they are out of defined possible choices.

Those three records should be somehow changed to reflect allowed options. I guess `Tradename` should be changed to `Tradenames` but I have no idea of how `ID` or `Research_code` should be mapped.

**Comment by revajk** [comment]
Research_code and Trade_name  were added  when doing chembl_lookup. They are the synonym types in Chembl. And Chembl doesn’t have a detailed breakdown of synonym types like in IDG (Research_code 1,2, 3,4 etc).

The choices are not used in synonym_type = models.ForeignKey('SynonymType',
                                     help_text=u'Type of name/synonym (e.g., TRADE_NAME, TRADENAME US, CLINICALTRAILS ID etc.’). I can either remove the choices or add the research_code and trade_name to it. 

Reva.

**Comment by mnowotka** [comment]
OK, what is `ID` then? Yes, please remove those choices as they are confusing.

**Comment by revajk** [comment]
I think that was added by Anneli. at some point to test probably @anneli. Do you want them?

**Comment by Anneli15** [comment]
Not sure I quite follow this thread but will try to input....: In chembl there is only Trade_names which on the web page comes up in a bundle with synonyms/research code for the compound. Not sure how they look at the back end... Anyway, the other ID:s were moved to cross reference tab I think?

**Comment by Anneli15** [comment]
So no separation between US, EU etc when it comes to trade names.

**Comment by revajk** [comment]
Okie Thanks.

**Comment by mnowotka** [comment]
OK, but there is a synonym_type called 'ID'. I have no idea what it is. Now imagine I have to migrate all the synonyms from ID to the Drug Base. But I don't know how to map it. With research codes it's easy: Research Code Alternate 1/2/3/4 -> RC, all trade names map to TN but I don't know how to map ID because I have no idea what 'ID' is.

**Comment by revajk** [comment]
I have moved the ‘ID’ from synonym_type to Reference_type. I presume ID would be any other ID that doesn’t fall in any of the ID’s categorised in Reference_type.Is that right Anneli?

**Comment by Anneli15** [comment]
Yes, there may be a compound that I don't have one of the already categorized IDs for, unlikely but possible.
