### ISSUE TITLE
DrugBase id is 'UnKnown'?

### ISSUE THREAD

**Issue by mnowotka** [chembl/IDG#72]
For some Molecule Dictionary records the `drugbase_id` has a value of 'UnKnown'.

Is there any reason why we are using this instead of `null`?

**Comment by revajk** [comment]
It hasn’t got a reason but its the default value for  missing Chembl-id. So I used the same for Pubchem and Drugbase id.

**Comment by mnowotka** [comment]
The default value for missing value in database column should be `null`.
