### ISSUE TITLE
Data export fails

### ISSUE THREAD

**Issue by mnowotka** [chembl/IDG#73]
If I press this:

![screen shot 2015-10-08 at 16 48 00](https://cloud.githubusercontent.com/assets/837119/10371685/6c6f94ea-6ddc-11e5-9a8d-17e712c4bd6a.png)

I'm getting this:
![screen shot 2015-10-08 at 16 48 14](https://cloud.githubusercontent.com/assets/837119/10371691/750bcbd2-6ddc-11e5-805b-05c2dd43aa48.png)

**Comment by revajk** [comment]
Fixed.

**Comment by mnowotka** [comment]
Hi,

The export is still pretty useless as it only exports current page not the whole table. Can you fix that?

**Comment by revajk** [comment]
I cannot understand why you can’t export. I just tried to export Molecule dictionary and Target Dictionary and I was able to export them. 
To export all the data you have check the box Export all data otherwise it will export just the current page.

**Comment by mnowotka** [comment]
Hi,

I somehow overlooked this option, sorry about that.
