### ISSUE TITLE
Choose TatgetComponents / ComponentSequences in the TargetDictionary add form

### ISSUE THREAD

**Issue by mnowotka** [chembl/IDG#79]
This is how the Target Dictionary add form looks like currently:

![screen shot 2015-10-09 at 12 34 42](https://cloud.githubusercontent.com/assets/837119/10392767/2db9bc66-6e82-11e5-8966-1c5469d2645b.png)

But Target Dictionary is in many-to-many relation with Component Sequences and one-to-many relation with Target Component. So there should be possible to choose one or many Component Sequences for the Target when creating it. Can you please modify this form to include this?

**Comment by revajk** [comment]
Hi Both, Question on how the relationship between Target dictionary, target_components and Component_sequences work. 

One target dictionary can have multiple target components  is that right ?  One to many relationship.
And one component sequence can have multiple target components right? same here too. Checked with Chembl database and I think that's what chembl has got too.

I have many to many relationship defined between target dictionary and component sequences, which is not required? 
Let me know should I change this before populating data.

**Comment by Anneli15** [comment]
One target can have multiple components i.e. for example protein families and complexes. Don't think there would be a many to many case as you would always just define one target at a time (which can be a single protein or a family).

**Comment by Anneli15** [comment]
Relating to that, I can't see target dictionary or components in production v72 at the moment.

**Comment by revajk** [comment]
Should be visible now.

**Comment by Anneli15** [comment]
Yep, thanks!

**Comment by mnowotka** [comment]
It this issue finished already?

**Comment by revajk** [comment]
Yes they are.

**Comment by mnowotka** [comment]
Wait, why do I see only two target component in the interface?
