### ISSUE TITLE
Can't see the 

### ISSUE THREAD

**Issue by Anneli15** [chembl/IDG#8]
![screen shot 2015-06-11 at 2 48 49 pm](https://cloud.githubusercontent.com/assets/12811998/8108544/03a6769a-1049-11e5-8bd8-b173e670fd6d.png)
loaded dictionaries, see error message in screen shot

**Comment by revajk** [comment]
Give me few minutes migrating the changes. Will let you know once its complete.

**Comment by revajk** [comment]
done.
