### ISSUE TITLE
Add chemspider id to cross seferences.

### ISSUE THREAD

**Issue by mnowotka** [chembl/IDG#81]
@revajk - you said you can't add chemspider id to IDG cross references because the chemspider client doesn't return this information. This is not true:

```
from chemspipy import ChemSpider
cs = ChemSpider('...')
c1 = cs.get_compound(28668377)
c1.csid # <- HERE
```

Please create new cross reference when doing ChemSpider lookup.

**Comment by revajk** [comment]
Cross -reference - chemspider added
