### ISSUE TITLE
compound missing?

### ISSUE THREAD

**Issue by Anneli15** [chembl/IDG#83]
I'm starting to add mechanism references to kinase inhibitors but the first one on my list doesn't seem to be in the data base? The compound is CHEMBL572881  AMG-706  Motesanib? is this to do with the different spreadsheet that you initially loaded?

**Comment by mnowotka** [comment]
What is the status of this issue?

**Comment by revajk** [comment]
Sorry forgot to reply to this. This is because I had a different excel sheet. Anneli, If you think you have many compounds missing from your excel sheet I can load them through the script. 
Put all the missing ones in a sheet and do send them to me. I will try to load them when I find time.

**Comment by Anneli15** [comment]
Ok, will try to get a list sorted for you.

**Comment by Anneli15** [comment]
Hi Reva. Doesn't seem to be any correlation between missing in dig and spreadsheet difference. Will add any missing data as I go through and add mechanism references.

**Comment by revajk** [comment]
Sure.
