### ISSUE TITLE
Change the type of molfile field

### ISSUE THREAD

**Issue by mnowotka** [chembl/IDG#84]
In the `idg/models/molecule_structure_file.py`, there is this line of code:

```
molfile = models.FileField(help_text=u'MDL Connection table representation of compound', blank=True, null=True)
```

I remember that `FileField` type is exactly what we agreed on. However I have to change this requirement because `FileField` is very inconvenient to use.

Please change the type of `molfile` field from `FileField` to `TextField`.

**Comment by revajk** [comment]
Done!
