### ISSUE TITLE
mechanism references

### ISSUE THREAD

**Issue by Anneli15** [chembl/IDG#86]
Been adding references today but for some reason it isn't working anymore, get error "404 Not found". Are you doing some updates or is this another problem? It is always very slow but now it's not loading the page at all.

**Comment by Anneli15** [comment]
Oh, I tried logging out and in again but didn't help. On V73.

**Comment by revajk** [comment]
No, I was’t working on Mechanism Reference.  The development and local server does take long but does end up adding reference. 
I think we have to think some better way to handle many to many relationship.

**Comment by Anneli15** [comment]
it's working again, not sure what the 404 error means but gone now.

**Comment by revajk** [comment]
I have added this  prefetch related  - to the mechanism reference in the local and it fetches all the records of the related compounds. like this: 

SR-49059 AVPR1A ANTAGONIST, SR-49059 OXTR ANTAGONIST 
JNJ-27018966 OPRM1 AGONIST, JNJ-27018966 OPRD1 ANTAGONIST, JNJ-27018966 OPRK1 AGONIST 

Anneli do you think that would be okie?

Reva.

**Comment by Anneli15** [comment]
Looks OK, not sure how it works though (i.e. what is different?)

**Comment by revajk** [comment]
instead of having to go to the database for the items, it will find them in a prefetched QuerySet cache that was populated in a single query. 

I will try to deploy the changes so far and see whether  adding the reference is any speeder

**Comment by Anneli15** [comment]
Ok, that sounds good.

**Comment by revajk** [comment]
It’s still slow, but little faster than before. With earlier it took 25.14 sec to load the page and now it take 18.32 sec. Anneli, could you check and let me know how you feel.

**Comment by Anneli15** [comment]
I tried before and now after lunch, get error "404 not found" :-( Is this because elf time-out i.e. takes too long?
