### ISSUE TITLE
Target dictionary

### ISSUE THREAD

**Issue by Anneli15** [chembl/IDG#89]
Tried adding a target that wasn't in the dictionary using Chembl ID. This worked except it hasn't saved the name (only preferred name) and when choosing it for compound, it hasn't saved. The target is INSR Insulin receptor CHEMBL1981, screen shots below.

![screen shot 2015-10-22 at 4 32 14 pm](https://cloud.githubusercontent.com/assets/12811998/10669846/89ae43a4-78da-11e5-823f-0c75762c4bc3.png)

![screen shot 2015-10-22 at 4 33 05 pm](https://cloud.githubusercontent.com/assets/12811998/10669872/ad1fa26a-78da-11e5-9144-27e3e1d27f1e.png)

![screen shot 2015-10-22 at 4 34 04 pm](https://cloud.githubusercontent.com/assets/12811998/10669903/cf5bd2d6-78da-11e5-822a-d1a0ad4a7a07.png)

**Comment by revajk** [comment]
Anneli, That’s because  Preferred names are the only names available for “targets" from CHEMBL.  You can add your short name and do CHEMBL lookup with CHEMBL ID.

like this in the screen shot. 

U

**Comment by Anneli15** [comment]
I did add the symbol (INSR) but it didn't save it and I can't go back in to try to change it.

**Comment by revajk** [comment]
Strange. Send me the CHEMBL ID you tried I just did and it seem to work

**Comment by Anneli15** [comment]
CHEMBL1981

**Comment by revajk** [comment]
I didn’t try it on the Production since it has got the target added already. Removing them means removing all the other related records being deleted. So I tried in the development version 
http://sark.ebi.ac.uk:7001/idg/idg/targetdictionary/?_q_=INSR http://sark.ebi.ac.uk:7001/idg/idg/targetdictionary/?_q_=INSR

Which version are you using ? 0.081

**Comment by Anneli15** [comment]
Yes, v81. The entry is correct except i can't add the name so it doesn't show up when adding the target for a specific compound (see second screen shot). Just remove it and I can add it again plus the compound details as it is only one so far

**Comment by revajk** [comment]
Done! Should be available now.

**Comment by Anneli15** [comment]
Great, thanks.
