### ISSUE TITLE
Target Dictionary - unique Constriants

### ISSUE THREAD

**Issue by revajk** [chembl/IDG#90]
Hi Both, While adding unique constraints to other  tables I found target dictionary doesn't have any unique constraints as well. Is chembl_id and uniprot_accession together unique?

**Comment by Anneli15** [comment]
Yes, they are unique. The only label that may not be unique is name or symbol as some can be ambiguous. The idea is to standardize these too and HGNC-symbols should be unique but better to only make Uniprot and Chembl ID unique for now.

**Comment by mnowotka** [comment]
Hi @revajk ,
Can you tell me how are you adding those constraints?

**Comment by revajk** [comment]
@michal 

In TargetDictionary Model

 class Meta:

```
    unique_together = (
    'chembl_id', ‘uniprot_accession’)
```

**Comment by mnowotka** [comment]
OK, thanks.

**Comment by revajk** [comment]
Is this alright to add them ? Or should I add individual unique fields? 
IS there any other field that should be made unique like the name or pref_name? 

Thanks

**Comment by Anneli15** [comment]
No, not name or pref name for the above reasons (see my comment above)
