### ISSUE TITLE
Test data in production?

### ISSUE THREAD

**Issue by mnowotka** [chembl/IDG#91]
Looking through revisions I came across this:

![screen shot 2015-10-23 at 11 47 48](https://cloud.githubusercontent.com/assets/837119/10690805/3b4ff714-797c-11e5-8666-66ee83623920.png)

I don't think those compounds should be in production, please remove them.
It would be also important to understand how they ended up here.

**Comment by revajk** [comment]
Deleted. Should have been while testing in production and didn’t delete after testing. 
As I always dump data from production and reload them back again while doing the deployment.

**Comment by mnowotka** [comment]
Hi Reva,

You should never run any tests on the production database. Please read about testing in Django framework (https://docs.djangoproject.com/en/1.8/topics/testing/overview/), specially how to set up dedicated test database.
