### ISSUE TITLE
Adding structure to compound

### ISSUE THREAD

**Issue by Anneli15** [chembl/IDG#92]
I've tried now a couple of times to add structure details like inchl key to compounds and it won't allow me  (see screen shot). The compound is there but no structure details are shown so not sure why to says there is already a structure loaded? One compound I've tried is: JNJ-42756493.
This entry is missing structure, chembl id (not found but I've added PubChem ID), chemspider etc so was going to add missing details. All OK to add other info but not anything to do with structure?

![screen shot 2015-10-26 at 1 40 22 pm](https://cloud.githubusercontent.com/assets/12811998/10730338/54461312-7be7-11e5-9f86-964771f551ca.png)

**Comment by revajk** [comment]
Hi Anneli, 

That should be because I have changed them to one to on field. I would try to look up for a way to edit a one to one field and update Structure page. I will let you knowonceI got them deployed.

**Comment by Anneli15** [comment]
Ok thanks. I guess this kind of relates to the new issue I've just posted i.e. no updates of info available for compounds already in the system.

**Comment by revajk** [comment]
Could you send me the inchikey and smiles  please.

**Comment by Anneli15** [comment]
JNJ-42756493 
CID67462786
OLAHOMJCDNXHFI-UHFFFAOYSA-N CC(C)NCCN(C1=CC2=NC(=CN=C2C=C1)C3=CN(N=C3)C)C4=CC(=CC(=C4)OC)OC

**Comment by revajk** [comment]
Anneli, I have no problem editing a compounds structure details. Could you check again. I have added this compound.

**Comment by Anneli15** [comment]
It's in there now, thanks. Not sure why I couldn't, will let you know if I have the same problem again.

**Comment by revajk** [comment]
Sure!.

**Comment by Anneli15** [comment]
Same problem again, have updated a compound with CID but no structural info was added. So I went in to add inchl key (and smiles) manually it says it is already there. But I can't see it even after refreshing :-( Compound is HHGV-678.

**Comment by revajk** [comment]
Send  me the SMILES and inchi I shall try again and see why you can’t add them

**Comment by Anneli15** [comment]
BJCJYEYYYGBROF-UHFFFAOYSA-N
Cc1c(cc(cn1)NC(=O)c2ccc(c(c2)C(F)(F)F)CN3CCN(CC3)C)Nc4nccc(n4)c5cccnc5

**Comment by Anneli15** [comment]
Still a problem

**Comment by revajk** [comment]
example please. What you tried and error.

Thanks

**Comment by Anneli15** [comment]
The one above

**Comment by Anneli15** [comment]
HHGV-678 has no structure in the dig, adding inchlkey does not work, system says it is already there

**Comment by Anneli15** [comment]
IDG not dig...

**Comment by Anneli15** [comment]
sorted
