### ISSUE TITLE
kinase inhibitors

### ISSUE THREAD

**Issue by Anneli15** [chembl/IDG#93]
Just a question about kinase inhibitors (and other compounds). With the Chembl and chemSpider lookup, will the entries that were loaded be updated at some point? Thinking mainly about the kinase inhibitors that seem to be lacking cross references (Chemspider ID and CAS number etc). Also, the INN/USAN names and years a bit muddled as John only had one column for both and used only one year. That info could be updated through Chembl lookup though can't it? 

So, If I go in to an entry and press save and edit or save, no more information is retrieved from Chembl or Chemspider but if I add a new compound, there is an automatic fill of available data.

So question really is, what happens to compounds already loaded via spreadsheets i.e. will Chembl id (or structure key) update this information automatically at some point?

**Comment by revajk** [comment]
By late this week I should have the data back -populated for all those that are already in IDG. I will keep you posted on that. 

Reva.
