### ISSUE TITLE
loading target references

### ISSUE THREAD

**Issue by Anneli15** [chembl/IDG#94]
Loading the excel spreadsheet with clinical candidates Ph1-3 including targets and references.

**Comment by Anneli15** [comment]
Have checked a couple of compounds, came across duplication of targets, see spreadsheet. Not sure how wide spread, have found 2 out of 3 compounds checked. Adding references manually seem to work, like the new boxes.
![screen shot 2015-11-13 at 1 39 22 pm](https://cloud.githubusercontent.com/assets/12811998/11147221/4ef7ddc2-8a0c-11e5-88dc-c0f8e5fed822.png)

**Comment by Anneli15** [comment]
References not all against all despite changing of numbering. So we still have 2 targets with one reference each even though it should be 2 targets with the same 2 references for each target.
So the result should be:
MAP2K1     Inhibitor      OTHER:http://cancerres.aacrjournals.org/ | PMID:20331454
MAP2K2     Inhibitor      OTHER:http://cancerres.aacrjournals.org/ | PMID:20331454

Not as it now reads:
MAP2K1     Inhibitor      OTHER:http://cancerres.aacrjournals.org/
MAP2K2     Inhibitor      PMID:20331454

Looking at compounds with 2 or more targets, it is still the same as before the deployment i.e. for two or more targets against one reference, only one of the targets has a reference linked to it (the other target has no reference in the database as it is now). This was a problem with the previous entries from the GPCR and NR spreadsheets, not only the newly loaded kinase inhibitors
I thought spending time changing the spreadsheet entries to include numbering was suppose to correct this?

Example:
MAP2K1 Inhibitor PMID19706763
MAP2K2 Inhibitor no reference

Should be:
MAP2K1 Inhibitor PMID19706763
MAP2K2 Inhibitor PMID19706763

So how should the spreadsheet entries look to achieve this?

**Comment by Anneli15** [comment]
Data references have been loaded for clinical candidates ph1-3

**Comment by revajk** [comment]
These are the targets that I couldn’t find in the CHEMBL and has been missed to be loaded.

NTRK 
VEFGR2 
FGFR4
(RAF) 
undefined - 757 line 
KEAP1/NFE2L2 - it was different in the database as  keap1/NF2L2 and have altered the target dictionary in idg to the one in the Excel sheet. 

This compound (BGBE24 R428 CID46215462) already exists as R428 in line 523 and again in 656 as BGBE24 R428 CID46215462

I haven’t added the second one BGBE24.

**Comment by Anneli15** [comment]
NTRK:s are in Chembl (and IDG) but searching for it with HGNC symbol doesn't always work in Chembl:
CHEMBL2815   NTRK1
CHEMBL4898   NTRK2
CHEMBL5608  NTRK3
CHEMBL3973   FGFR4
CHEMBL3038498  KEAP1/NFE2L2

VEFGR2 typo for VEGFR2 but should be KDR which is the HGNC symbol. I have changed it.

Undefined: leave as target

R428 BGB324 is fine, have just added the highs phase to 2.

**Comment by Anneli15** [comment]
FGFR4 is in IDG but doesn't have the symbol, only pref name (Fibroblast growth factor receptor 4). I tried to add it but I can't, error 500.

The compound FGF401 that has this target is in the iDG with the correct target but it won's say, only says FGF401 INHIBITOR and I can't add target reference because the target isn't mentioned.
![screen shot 2015-12-07 at 3 39 44 pm](https://cloud.githubusercontent.com/assets/12811998/11631197/cdf32182-9cf8-11e5-80f3-17bba45e00d5.png)

![screen shot 2015-12-07 at 3 40 57 pm](https://cloud.githubusercontent.com/assets/12811998/11631252/14e87d76-9cf9-11e5-804f-dae007b50fc4.png)

Have tried adding new target NTRK1-3 too but  get Error 500.

**Comment by Anneli15** [comment]
Found duplicated entries, guess these are ones that you have reloaded with the target above (NTRK1 etc?)

![screen shot 2015-12-08 at 12 08 21 pm](https://cloud.githubusercontent.com/assets/12811998/11655365/18d19128-9da5-11e5-9e16-ab36063cb4e0.png)

**Comment by revajk** [comment]
HI Anneli, The NTRK1 could be because of reloading. IS there any other cases with Duplication?

**Comment by Anneli15** [comment]
Think it is only the compounds you reloaded and that had NTRK:s as targets.

**Comment by Anneli15** [comment]
![screen shot 2015-12-09 at 1 54 52 pm](https://cloud.githubusercontent.com/assets/12811998/11687062/8587cd3c-9e7c-11e5-9f01-cbb2953a8258.png)

**Comment by Anneli15** [comment]
Maybe not only compounds with NTRK...

**Comment by revajk** [comment]
Do you reckon there are a lot of duplication? I suppose the kinase compounds might have duplications.  I shall re-try if thats the case. If they are few would you be able to delete them? 

Thanks 
Reva.

**Comment by Anneli15** [comment]
Not sure, I have deleted the ones I have come across today.

**Comment by revajk** [comment]
Do you want me to retry the loading process? But I can deploy this only tomorrow.

**Comment by Anneli15** [comment]
let me have a look and see if there are many

**Comment by Anneli15** [comment]
unfortunately it seems to concern all that have changed since the initial load months ago i.e. the new final spreadsheet targets are there but also whatever was there before. The only ones that are OK are the ones that had the correct HGNC symbol at the start (the original unedited spreadsheet from John). So yes, a reload is necessary. Will all the changes I've made since the last deployment stay? I mean the ones I've changed manually since last deployment?

**Comment by revajk** [comment]
Yes.

**Comment by Anneli15** [comment]
Ok, just let me know when you are ready to do it and I need to log out.

**Comment by revajk** [comment]
I wouldn’t be able to deploy them until tomorrow. I shall let you know when I do it. 
if you have any change in data in production between now and tomorrow do let me know as well. 

Thanks

**Comment by mnowotka** [comment]
OK, I think it may be about time for me to step in. Let me put it like this: this data has to be loaded in the form that satisfies Anneli until the end of this week. If there are any reasons why we should suspect this may be hard to do programmatically, maybe we should stop here and start entering the data manually?

**Comment by revajk** [comment]
I think, Its because of overlook in coding, where I check a mechanism with a target dictionary exists already, if it does I try to update if not I insert new data. Since there had been kinase with non HGNC name I hadn’t been able to spot the in the code. 

I will try to check for a mechanism for a particular compound this time.

**Comment by Anneli15** [comment]
Not sure I quite understand the last bit but what I would like to see in the final product are the compounds loaded with the targets and associated references as in the last final curated spreadsheet I sent (and that has been loaded), nothing else please (except the typos/duplicated compound and missing targets which have now been added as per above in this message trail so this should be OK too).

**Comment by mnowotka** [comment]
I'm not sure if I understand either. @revajk - I need a clear message - can you do what @Anneli15 is asking until the end of this week or not? The honest answer here is very important as we have to decide what to do.

**Comment by revajk** [comment]
I think so. I am loading at the moment I can confirm in a bit.

**Comment by mnowotka** [comment]
OK, thanks.

**Comment by Anneli15** [comment]
Thanks

**Comment by Anneli15** [comment]
I have edited a few compounds and target families yesterday, please can this be taken into account when you are loading (i.e. please keep the changes made/dated yesterday). I'll wait til tomorrow Friday morning to hear if you will be able to load, I understand that you may have to stay and take care of Harri. I can go in a delete the duplications manually if you won't be able to reload and deploy, shouldn't hopefully take that long.

**Comment by Anneli15** [comment]
Ok, I've had a look. Think the duplicated entries are gone, can't see any. The changes I made on Wednesday are gone too but not that many so can handle that. There are no company, mechanism notes, cross references etc for most of the kinase inhibitors if not all and they seem to be missing for some of the GPCRs too, only looked at a few and some had entries and some didn't. So, not sure which ones have all information entered and which do not without going through them all. It must be something to do with the deployed data version as I am sure most if not all of the data was there before?

I guess at the moment, it is mostly the target and references that we need so maybe if I add the missing ones and we can fix the company and notes issue later? Think Reva is away now anyway so can't fix it by redeployment. I may add the notes too as they are often related to the target but skip cross refs and company. Any ideas?

**Comment by Anneli15** [comment]
I've been manually editing/adding in the database. Shold hopefully be done later today/tomorrow
